# services === container --> all your container will do under
# services
version: '3.8'
services:
  logxfrontendbtob:
    # stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '8080:3000'
    env_file:
      - ./.env
