FROM node:16.15

# Working Directory
WORKDIR /app

# Page json on top got optimize in current directory
COPY package.json .
COPY yarn.lock .

# installing the package
RUN yarn

# Copy in Working dir from current file e.g shipsavy-client
COPY . .

# available on port 3000
EXPOSE 3000

# Dev Server
CMD ["yarn", "start"]