//Customer-ME
export const CUSTOMER_DATA_FETCH_REQUEST = 'CUSTOMER_DATA_FETCH_REQUEST';
export const CUSTOMER_DATA_FETCH_SUCCESS = 'CUSTOMER_DATA_FETCH_SUCCESS';
export const CUSTOMER_DATA_FETCH_ERROR = 'CUSTOMER_DATA_FETCH_ERROR';
